const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cfg=window.GEOREDE_CONFIG||{};let session,role,clients=[],plans=[],data={},org,editing;
function notice(message,bad=false){$('#notice').hidden=false;$('#notice').textContent=message;$('#notice').className=bad?'danger':'';}
function configured(){if(!cfg.supabaseUrl||!cfg.publishableKey)throw Error('Configure o projeto Supabase antes de entrar.');const url=new URL(cfg.supabaseUrl);if(url.protocol!=='https:'||url.username||url.password||url.port||!['','/'].includes(url.pathname)||url.search||url.hash)throw Error('Informe a URL HTTPS pública do projeto, sem credenciais ou caminhos.');}
async function http(path,body,withAuth=true){configured();const r=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+path,{method:'POST',headers:{'content-type':'application/json',apikey:cfg.publishableKey,...(withAuth?{authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||j.error)throw Error(j.error||j.message||'Operação não concluída.');return j;}
async function api(action,values={}){if(session.expires_at*1000<Date.now()+60000)session=await http('/auth/v1/token?grant_type=refresh_token',{refresh_token:session.refresh_token},false);return http('/functions/v1/georede-access-v2',{action,organization_id:org,...values});}
async function loadClients(){const r=await api('clients');role=r.role;clients=r.clients;plans=r.plans;$('#roleName').textContent=role==='master'?'Master • administração central':'Administrador Desktop • filiais atribuídas';org=clients.some(c=>c.id===org)?org:clients[0]?.id;$('#clientSelect').innerHTML=clients.map(c=>`<option value="${esc(c.id)}">${esc(c.trade_name||c.legal_name)}</option>`).join('');$('#clientSelect').value=org||'';await refresh();}
async function refresh(){data=org?await api('dashboard'):{};render();$('#newUser').disabled=!org;$('#newBranch').disabled=!org;$('#rulesForm button.primary').disabled=!org;$$('[data-master]').forEach(e=>e.hidden=role!=='master');}
function render(){
 const branches=data.branches||[],users=data.users||[],rules=data.rules||{};
 $('#branchCount').textContent=branches.length;$('#seatCount').textContent=branches.reduce((n,b)=>n+b.used,0)+' / '+branches.reduce((n,b)=>n+b.mobile_limit,0);$('#expiry').textContent=data.license?.current_period_end?new Date(data.license.current_period_end).toLocaleDateString('pt-BR'):'—';$('#offline').textContent=(rules.offline_hours??72)+' horas';
 const bn=id=>branches.find(b=>b.id===id)?.name||'—';
 $('#userRows').innerHTML=users.map(u=>`<tr><td><b>${esc(u.full_name)}</b><br><span class="small">${esc(u.username)}</span></td><td>${u.role==='member'?'Operador Mobile':'Administrador Desktop'}</td><td>${esc(bn(u.branch_id))}</td><td class="${u.active&&u.profile_active?'success':'danger'}">${u.active&&u.profile_active?'Ativo':'Bloqueado'}</td><td><div class="actions"><button data-edit-user="${esc(u.user_id)}">Editar</button><button data-password="${esc(u.user_id)}">Senha</button>${role==='master'&&u.role!=='member'?`<button data-assign="${esc(u.user_id)}">Filiais</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="5">Nenhum usuário nas filiais autorizadas.</td></tr>';
 $('#branchRows').innerHTML=branches.map(b=>`<tr><td>${esc(b.name)}</td><td>${b.used} / ${b.mobile_limit}</td><td>${b.active?'Ativa':'Inativa'}</td>${role==='master'?`<td><button data-edit-branch="${esc(b.id)}">Editar limite</button></td>`:''}</tr>`).join('')||'<tr><td colspan="4">Nenhuma filial atribuída.</td></tr>';
 $('#deviceRows').innerHTML=(data.devices||[]).map(d=>{const count=(data.replacements||[]).filter(r=>r.user_id===d.user_id).length,limited=d.kind==='mobile'&&count>=rules.replacement_limit&&role!=='master';return`<tr><td>${esc(d.display_name||d.device_key.slice(-12))}<br><span class="small">${esc(d.kind)}</span></td><td>${esc(users.find(u=>u.user_id===d.user_id)?.full_name||'—')}</td><td>${esc({active:'Autorizado',pending:'Pendente',revoked:'Revogado'}[d.status]||d.status)}</td><td>${count} / ${rules.replacement_limit}</td><td>${d.status==='active'?`<button data-revoke="${esc(d.id)}">Revogar</button>`:`<button data-approve="${esc(d.id)}" ${limited?'disabled':''}>${limited?'Exige Master':'Autorizar'}</button>`}</td></tr>`;}).join('')||'<tr><td colspan="5">Sem solicitações de aparelhos.</td></tr>';
 for(const k of ['offline_hours','replacement_limit','replacement_window_days'])$('#rulesForm').elements[k].value=rules[k]??'';
 const expiry=new Date(data.license?.current_period_end);$('#rulesForm').elements.expires_at.value=Number.isNaN(expiry.valueOf())?'':new Date(expiry-expiry.getTimezoneOffset()*60000).toISOString().slice(0,16);
 $$('#rulesForm input').forEach(e=>e.disabled=role!=='master'||!org);$('#activation').textContent=!org?'Cadastre o primeiro cliente para definir suas filiais e acessos.':rules.enabled?'Controle por filial habilitado neste ambiente.':'Controle v2 desativado. O Master deve mapear os usuários existentes antes de ativar.';$('#enable').disabled=!org||rules.enabled===true;
}
const input=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const branchSelect=value=>`<label>Filial<select name="branch_id" required>${(data.branches||[]).filter(b=>b.active).map(b=>`<option value="${esc(b.id)}" ${b.id===value?'selected':''}>${esc(b.name)} (${b.used}/${b.mobile_limit})</option>`).join('')}</select></label>`;
function open(title,fields,save){$('#editorTitle').textContent=title;$('#editorFields').innerHTML=fields;$('#editorError').textContent='';editing=save;$('#editor').showModal();}
function userEditor(u){open(u?'Editar usuário':'Cadastrar usuário',input('Nome completo','full_name',u?.full_name,'text','required maxlength="120"')+input('Login','username',u?.username,'text','required pattern="[a-z0-9._-]{3,60}"')+(u?'':input('Senha temporária','password','','password','required minlength="8" autocomplete="new-password"'))+(!u&&role==='master'?'<label>Perfil<select name="member_role"><option value="member">Operador Mobile</option><option value="admin">Administrador Desktop</option></select></label>':'')+(!u||u.role==='member'?branchSelect(u?.branch_id):'')+(u?`<label class="check"><input name="active" type="checkbox" ${u.active?'checked':''}>Usuário ativo</label>`:''),async fd=>{let values=Object.fromEntries(fd);if(u)values={...values,user_id:u.user_id,active:fd.has('active')};await api(u?'save_user':'create_user',values);});const roleField=$('#editorForm').elements.member_role;if(roleField)roleField.onchange=()=>{const field=$('#editorForm').elements.branch_id;field.disabled=roleField.value==='admin';field.parentElement.hidden=field.disabled;};}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{session=await http('/functions/v1/georede-access-login',Object.fromEntries(new FormData(e.target)),false);e.target.reset();await loadClients();$('#login').hidden=true;$('#app').hidden=false;$('#logout').hidden=false;$('#notice').hidden=true;}catch(e){session=null;notice(e.message,true);}finally{button.disabled=false;}};
$('#logout').onclick=async()=>{try{await http('/auth/v1/logout',{});}catch{}session=null;location.reload();};
$('#clientSelect').onchange=async e=>{org=e.target.value;try{await refresh();}catch(e){notice(e.message,true);}};
$('#refresh').onclick=async()=>{try{await loadClients();notice('Informações atualizadas.');}catch(e){notice(e.message,true);}};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.setAttribute('aria-selected',x===b));$$('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==b.dataset.tab);});
$('#newUser').onclick=()=>userEditor();$('#cancel').onclick=()=>$('#editor').close();
$('#editorForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await editing(new FormData(e.target));$('#editor').close();e.target.reset();await loadClients();notice('Alteração salva no ambiente de homologação.');}catch(e){$('#editorError').textContent=e.message;}finally{b.disabled=false;}};
$('#newBranch').onclick=()=>branchEditor();
function branchEditor(b){open(b?'Editar filial':'Cadastrar filial',input('Nome da filial','name',b?.name,'text','required')+input('Limite de operadores Mobile','mobile_limit',b?.mobile_limit??0,'number','required min="0" max="10000"'),fd=>api('save_branch',{...Object.fromEntries(fd),branch_id:b?.id}));}
$('#newClient').onclick=()=>open('Cadastrar cliente',input('Razão social','legal_name','','text','required')+input('Nome fantasia','trade_name')+input('Documento','document')+`<label>Plano<select name="plan_id">${plans.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label>`+input('Vencimento','expires_at','','datetime-local','required'),fd=>{const v=Object.fromEntries(fd);v.expires_at=new Date(v.expires_at).toISOString();return api('create_client',v);});
$('#rulesForm').onsubmit=async e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.target));v.expires_at=new Date(v.expires_at).toISOString();await api('set_rules',v);await refresh();notice('Regras atualizadas.');}catch(e){notice(e.message,true);}};
$('#enable').onclick=async()=>{try{await api('enable_client');await refresh();}catch(e){notice(e.message,true);}};
document.body.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.editUser)userEditor(data.users.find(u=>u.user_id===b.dataset.editUser));
 else if(b.dataset.editBranch)branchEditor(data.branches.find(x=>x.id===b.dataset.editBranch));
 else if(b.dataset.password)open('Redefinir senha',input('Nova senha','password','','password','required minlength="8" autocomplete="new-password"'),fd=>api('reset_password',{user_id:b.dataset.password,password:fd.get('password')}));
 else if(b.dataset.assign){const current=(data.assignments||[]).filter(x=>x.user_id===b.dataset.assign).map(x=>x.branch_id);open('Filiais do Administrador Desktop',data.branches.map(x=>`<label class="check"><input type="checkbox" name="branch_ids" value="${esc(x.id)}" ${current.includes(x.id)?'checked':''}>${esc(x.name)}</label>`).join(''),fd=>api('set_admin_branches',{user_id:b.dataset.assign,branch_ids:fd.getAll('branch_ids')}));}
 else if(b.dataset.approve||b.dataset.revoke){b.disabled=true;await api(b.dataset.approve?'approve_device':'revoke_device',{device_id:b.dataset.approve||b.dataset.revoke});await refresh();notice('Situação do aparelho atualizada.');}
 }catch(e){notice(e.message,true);}finally{b.disabled=false;}});
